doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '16'
        driver: 'pdo_pgsql'
        profiling_collect_backtrace: '%kernel.debug%'
        use_savepoints: true
        types:
            geography: Jsor\Doctrine\PostGIS\Types\GeographyType
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Providers:
                type: xml
                is_bundle: false
                dir: '%kernel.project_dir%/src/Providers/Infrastructure/Persistence/Doctrine'
                prefix: 'App\Providers\Domain'
                alias: App\Providers\Domain
            Comments:
                type: xml
                is_bundle: false
                dir: '%kernel.project_dir%/src/Comments/Infrastructure/Persistence/Doctrine'
                prefix: 'App\Comments\Domain'
                alias: App\Comments\Domain
            Fountains:
                type: xml
                is_bundle: false
                dir: '%kernel.project_dir%/src/Fountains/Infrastructure/Persistence/Doctrine'
                prefix: 'App\Fountains\Domain'
                alias: App\Fountains\Domain
            Users:
                type: xml
                is_bundle: false
                dir: '%kernel.project_dir%/src/Users/Infrastructure/Persistence/Doctrine'
                prefix: 'App\Users\Domain'
                alias: App\Users\Domain
        controller_resolver:
            auto_mapping: false

when@test:
    doctrine:
        dbal:
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
