framework:
    messenger:
        transports:
        # Define transports here if needed for async, but for sync handling, this can be omitted
        routing:
        # Map your messages to transports if using async
        default_bus: command_bus

        buses:
            command_bus:
                # Middleware for the command bus
                default_middleware: true
            event_bus:
                # Middleware for the event bus
                default_middleware: true