framework:
    messenger:
        default_bus: command_bus
        buses:
            command_bus:
                default_middleware: true

            event_bus:
                default_middleware: true

            messenger.bus.event.async:
                default_middleware: allow_no_handlers

        transports:
            amqp:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: exchange_librarify
                        type: topic
                    queues: [ ]
        routing:
            '*': amqp
