security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
        App\Users\Domain\User:
            algorithm: bcrypt
            cost: 12
    providers:
        users_in_memory: { memory: null }
        custom_user_provider:
            id: App\Users\Infrastructure\Security\CustomUserProvider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        api:
            pattern: ^/api
            lazy: true
            stateless: true
            provider: custom_user_provider
            jwt: ~

    access_control:
        - { path: ^/api/auth/(login|register),  roles: PUBLIC_ACCESS }
        - { path: ^/api, roles: ROLE_USER }


when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
