version: '3'

services:
    rabbitmq:
        container_name: rabbitmq
        image: 'rabbitmq:3.10.5-management'
        restart: unless-stopped
        ports:
            - 5672:15672
        environment:
            - RABBITMQ_DEFAULT_USER=guest
            - RABBITMQ_DEFAULT_PASS=guest
        networks:
            - shared_network
            - fountains_network
            
    php:
        container_name: fountains_php
        user: "${UID}:${GID}"
        build:
            context: .
            dockerfile: .docker/php/Dockerfile
            args:
                TIMEZONE: Europe/Madrid
        volumes:
            - ./:/var/www/project/
        extra_hosts:
            - "host.docker.internal:host-gateway"
        networks:
            - fountains_network

    nginx:
        container_name: fountains_nginx
        build:
            context: .
            dockerfile: .docker/nginx/Dockerfile
        volumes:
            - ./:/var/www/project/
        ports:
            - 88:80
        networks:
            - fountains_network
    db:
        container_name: fountains_db
        image: postgis/postgis:latest
        volumes:
            - db_library:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: nil
            POSTGRES_PASSWORD: chopin
            POSTGRES_DB: fountains_db
        ports:
            - 5432:5432
        networks:
            - fountains_network
volumes:
    projectback_app_sync:
        external: true
    db_library:

networks:
    fountains_network:
    shared_network:
        name: fountains_shared_network
        driver: bridge
