services:
    php:
        container_name: fountains_php
        build:
            context: .
            dockerfile: .docker/php/Dockerfile
            args:
                TIMEZONE: Europe/Madrid
        volumes:
            - ./:/var/www/fountains/
        extra_hosts:
            - "host.docker.internal:host-gateway"
        networks:
            - fountains_network

    nginx:
        container_name: fountains_nginx
        build:
            context: .
            dockerfile: .docker/nginx/Dockerfile
        volumes:
            - ./:/var/www/fountains/
        ports:
            - "${NGINX_PORT}:80"
        environment:
            NGINX_PORT: ${NGINX_PORT:-8000}
        env_file:
            - .env
            - .env.local
        networks:
            - fountains_network
    
    db:
        container_name: fountains_db
        image: postgis/postgis:latest
        volumes:
            - fountains_database:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        env_file:
            - .env
            - .env.local
        ports:
            - 5432:5432
        networks:
            - fountains_network
    
    rabbitmq:
        container_name: rabbitmq
        image: 'rabbitmq:3.10.5-management'
        restart: unless-stopped
        ports:
            - 5672:15672
        environment:
            - RABBITMQ_DEFAULT_USER=guest
            - RABBITMQ_DEFAULT_PASS=guest
        networks:
            - shared_network
            - fountains_network

volumes:
    fountains_database:

networks:
    fountains_network:
    shared_network:
        name: fountains_shared_network
        driver: bridge
