fountain_controller_post:
  path: /api/fountains
  controller: App\Fountains\Infrastructure\Controllers\FountainsPostController
  methods:  [POST]

fountain_controller_put:
   path: /api/fountains
   controller: App\Fountains\Infrastructure\Controllers\FountainsPutController
   methods: [PUT]

fountain_controller_get:
  path: /api/fountains
  controller: App\Fountains\Infrastructure\Controllers\FountainsGetController
  methods:  [GET]
